### ISSUE TITLE
cpctech.cpc-live.com urls no longer functioning

### ISSUE THREAD

**Issue by pelrun** [cpcitor/cpc-dev-tool-chain#23]
Looks like cpc-live.com is down, which breaks the inital downloads of addhead/2cdt/cpcxfs.

Changing the makefiles to point to cpctech.cpcwiki.de instead fixes the problem (for now).

**Comment by fidergo-stephane-gourichon** [comment]
Thanks @pelrun for notifying!

Since you have it working, if you can provide a PR, or simply a patch here, or even a reply like "file a/b/c/Makefile, line X becomes FOOR=BAR", it will help a lot.

**Comment by pelrun** [comment]
[cpctech.patch.txt](https://github.com/cpcitor/cpc-dev-tool-chain/files/5183313/cpctech.patch.txt)

This should do it.

**Comment by fidergo-stephane-gourichon** [comment]
Ah, several places. Thanks. Cannot incorporate that now. If you can do a PR it's great!
Apparently you can prepare a PR from the web interface, look at the pencil on https://github.com/cpcitor/cpc-dev-tool-chain/blob/master/cpclib/cfwi/local.Makefile
 Else I'll incorporate the changes later and credit you.
Thank in any case!

**Comment by cpcitor** [comment]
Closed by #24, thanks @pelrun !
