### ISSUE TITLE
SDCC  "issue"

### ISSUE THREAD

**Issue by lronaldo** [cpcitor/cpc-dev-tool-chain#6]
> SDCC issue should be treated with the "minimal test case" approach: just plain try to compile SDCC without any reference to cpc-dev-tool-chain , see if problem persists. Probably report to SDCC project directly.

The problem with the comma operator when compiling SDCC is not due to cpc-dev-tool-chain. As I stated before, it is quite bizarre. It seems to happen randomly, even on the same platform. The only thing I can suspect is conditional compilation depending on architecture detection, and bad detection of the architecture.

I suggest adding a particular page in the install instructions explaining the way to solve the issue if it happens. Other interesting idea could be adding a message in the Makefile to pop up when SDCC fails to compile, and then point the user to the solution in the install instructions. Even being an SDCC issue, users would normaly think that cpc-dev-tool-chain does not work.

Next step would be reporting to SDCC developers. 

I found the problem on Win 7/Cygwin and Linux Manjaro/Arch. Users have also reported me the same problem several times on Windows/Cygwin. However, I've been able to compile SDCC without any problem before in the same machines.

**Comment by lronaldo** [comment]
I have installed cpc-dev-tool-chain on Debian Wheezy (stable), without problems compiling SDCC. Here I left details on system configuration:

```
ronaldo@gc:~/temp/cpc-dev-tool-chain$ uname -r
3.2.0-4-amd64
ronaldo@gc:~/temp/cpc-dev-tool-chain$ gcc --version
gcc (Debian 4.7.2-5) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by lronaldo** [comment]
On Linux Manjaro, there is also a second compilation error for SDCC:

```
gcc -c -fms-extensions -pipe -ggdb -g -O2 -Wall -Wno-parentheses -DINDEXLIB -DUNIX -I. -I/home/ronaldo/temp/kk/cpc-dev-tool-chain/tool/sdcc/sdcc-3.4.0/sdas/linksrc -fms-extensions -pipe -ggdb -g -O2 -Wall -Wno-parentheses -o obj/lkar.o /home/ronaldo/temp/kk/cpc-dev-tool-chain/tool/sdcc/sdcc-3.4.0/sdas/linksrc/lkar.c
In file included from /usr/include/string.h:634:0,
                 from /home/ronaldo/temp/kk/cpc-dev-tool-chain/tool/sdcc/sdcc-3.4.0/sdas/linksrc/aslink.h:35,
                 from /home/ronaldo/temp/kk/cpc-dev-tool-chain/tool/sdcc/sdcc-3.4.0/sdas/linksrc/lkar.c:34:
/home/ronaldo/temp/kk/cpc-dev-tool-chain/tool/sdcc/sdcc-3.4.0/sdas/linksrc/lkar.c:50:1: error: expected identifier or '(' before '__extension__'
 strndup (const char *str, size_t len)
 ^
Makefile:136: recipe for target 'obj/lkar.o' failed
```

It is easily solved, but it is really curious, as it complaints about compiling `strndup` with kind of a cryptic message. The actual problem is strndup being already defined. The solution is as easy as commenting the new definition on lkar.c:

```
48a49
> /*
56a58
> */
```

**Comment by cpcitor** [comment]
The strangest thing is that it does not always happen.

Might it be a bug not even in SDCC but in gcc, or in the way gcc was compiled ? The fact that `patch` failed similarly in Cygwin and Manjaro might be a hint. It would be interesting if you could figure out the version of gcc that was used to compile the failing `patch`, the working one, in Cygwin and in Manjaro.

In Ubuntu 14.04:

```
uname -r
3.13.0-35-generic
gcc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
```

> Other interesting idea could be adding a message in the Makefile to pop up when SDCC fails to compile, and then point the user to the solution in the install instructions. Even being an SDCC issue, users would normaly think that cpc-dev-tool-chain does not work.
> 
> Next step would be reporting to SDCC developers.

Good idea. I suggest linking to a bug query URL rather than URL to a specific bug, for example: https://github.com/cpcitor/cpc-dev-tool-chain/labels/sdcc . It will show at all times issues still opened (better signal-to-noise ratio, less maintenance work).

**Comment by cpcitor** [comment]
Hello @lronaldo . I just re-read https://github.com/cpcitor/cpc-dev-tool-chain/issues/1 which is the origin of this one. Did this issue appear again on more recent SDCC versions? Else we can just close it.

**Comment by lronaldo** [comment]
SDCC has changed a great deal since 2015. If you use latest versions, almost everything will have different results.

You may safely discard this issue and start experimenting with new versions.

**Comment by cpcitor** [comment]
Thanks!
