### ISSUE TITLE
Building on MacOS

### ISSUE THREAD

**Issue by kilon** [cpcitor/cpc-dev-tool-chain#8]
hey there , I want to help you to build this on MacOSX

I will fork it and follow your advice on how to get it to build. I am on a year old iMac and work with latest Yosemite , 3.4 Ghz quad core and 8 GBs Ram.  I have also latest XCODE.

**Comment by sgourichon** [comment]
Hello,

Thank you for your proposition. I'm not fluent in XCode but if I can help I'd do it gladly.

First step is to install documented dependencies. What ways do you know ? There are several solutions (homebrew for example). Is there a solution that does not require administrator rights ?

Then I know that XCode allows to create a project of type "other/External Build System" which default to GNU make, but I don't know anything more. In particular, how to tell it about the different targets (`make dsk` for example) ? Perhaps the simplest first step would be to tell XCode to dive into the directory `hello_world_using_sdcc` and issue `make` there.

Once these two steps work, chances are most of the work is done and after maybe a handful of small fixes it should be able to generate the wished targets.

Cheers!

**Comment by kilon** [comment]
i get an error using make on hello_world_using_sdcc

make[2]: **\* [sdcc_srctree.ref] Error 1
make[1]: **\* [..//tool/sdcc/build_config.inc] Error 2
make: **\* [hello_world_using_sdcc] Error 2

Unfortunately I am not experienced with building C applications thats why I needed a guide. But I will try XCode and maybe I am more lucky there.

**Comment by cpcitor** [comment]
Cleaning up old issues. 

Thanks for pasting the last lines.
I guess it might be something like a too old `tar` or something.
It can only be diagnosed better with more lines of the build log.

Since the entry is very old I'm closing it. 
The project was updated and recently tested on Ubuntu.
Feel free to try the updated version.
